// Script to force the app to use development database
const fs = require('fs');
const path = require('path');

// Create a simple file that will force the emulator to use dev DB
const forceDevConfig = `
// This file is generated by the use-dev-db.js script
// It forces the app to use the development database when running with emulators
import { Platform } from 'react-native';
import Constants from 'expo-constants';

// Force development config for emulator use
const FIREBASE_CONFIG = {
  apiKey: "AIzaSyD3FFprDwIZwECR5TkYCeOkiCUNGLp6qQM",
  authDomain: "barber-38b88.firebaseapp.com",
  projectId: "barber-38b88",
  storageBucket: "barber-38b88.appspot.com",
  messagingSenderId: "910680290414",
  appId: "1:910680290414:web:606ee1c0e84c32e6bfcc8c",
  measurementId: "G-B6HMP9YK92"
};

// Export the validated config directly
export default FIREBASE_CONFIG;
`;

// Path to the firebaseConfig file
const configPath = path.join(__dirname, 'src', 'services', 'firebaseConfig.js');

// Backup the original file
const backupPath = path.join(__dirname, 'src', 'services', 'firebaseConfig.js.bak');
if (!fs.existsSync(backupPath)) {
  fs.copyFileSync(configPath, backupPath);
  console.log('✅ Original firebaseConfig.js backed up to firebaseConfig.js.bak');
}

// Write the new config file
fs.writeFileSync(configPath, forceDevConfig);
console.log('✅ Development database config enforced for emulator use');
console.log('🔍 Config now points to: barber-38b88');
console.log('🔧 To restore original config, run: node restore-firebase-config.js');

// Create the restore script
const restoreScript = `
// Script to restore the original Firebase config
const fs = require('fs');
const path = require('path');

// Paths to the files
const configPath = path.join(__dirname, 'src', 'services', 'firebaseConfig.js');
const backupPath = path.join(__dirname, 'src', 'services', 'firebaseConfig.js.bak');

// Check if backup exists
if (fs.existsSync(backupPath)) {
  // Restore from backup
  fs.copyFileSync(backupPath, configPath);
  console.log('✅ Original firebaseConfig.js restored from backup');
} else {
  console.log('❌ Backup file not found. Cannot restore original config.');
}
`;

// Write the restore script
fs.writeFileSync(path.join(__dirname, 'restore-firebase-config.js'), restoreScript);
console.log('✅ Created restore script: restore-firebase-config.js');